# Generated by Django 5.2.4 on 2025-08-19 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Entry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("entry_title", models.CharField(max_length=200)),
                ("entry_text", models.TextField(default=None)),
                ("publish_date", models.DateTimeField(verbose_name="Date Published")),
                ("edit_date", models.DateTimeField(verbose_name="Date Edited")),
            ],
        ),
    ]
