# Generated by Django 5.2.4 on 2025-08-19 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pages", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="entry",
            name="edit_date",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Date Edited"),
        ),
    ]
