# Generated by Django 5.2.4 on 2025-08-19 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pages", "0002_alter_entry_edit_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="entry",
            name="slug",
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
