name: Build and Test

on:
    workflow_call:
    push:
        branches:
            - '**'

jobs:
    build-test:
        runs-on: ubuntu-latest
        steps:
            - name: Check out code
              uses: actions/checkout@v3

            # Set up Docker Buildx for caching
            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v2