name: Build and Test

on:
    workflow_call:
    push:
        branches:
            - '**'
            - '!main'
            - '!staging'

jobs:
    build-test:
        runs-on: ubuntu-latest
        steps:
            - name: Check out code
              uses: actions/checkout@v3

            # Set up Docker Buildx for caching
            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v2

            - name: Prepare Docker cache directory
              run: mkdir -p /home/runner/.cache/docker

            - name: Cache docker layers
              uses: actions/cache@v3
              with:
                path: /home/runner/.cache/docker
                key: ${{ runner.os }}-docker-${{ hashFiles('**/requirements.txt') }}
                restore-keys: ${{ runner.os }}-docker-
            
            - name: Build with inline cache
              run: |
                docker buildx build \
                  --cache-from type=local,src=/home/runner/.cache/docker \
                  --cache-to type=local,dest=/home/runner/.cache/docker,mode=max \
                  --load \
                  -t Blog-Website-Thing:latest \
                  -f Dockerfile \
                  .

            - name: Compose up
              run: docker compose up --exit-code-from django-test

            - name: Print test logs
              if: ${{ always() }}
              run: docker compose logs django-test